name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: jimmyse211
          password: 13fb18d4-be64-4d8c-bf4d-e8f0137f95dd
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: jimmyse211/cd_test_0610:latest